# AUTOGENERATED! DO NOT EDIT! File to edit: 06_lists.ipynb (unless otherwise specified).

__all__ = ['spam']

# Cell
# ['cat','bat','rat','elephant']
spam = ['cat','bat','rat','elephant']
spam
print(spam)
spam[0]