# AUTOGENERATED! DO NOT EDIT! File to edit: 10_1_Python_Phone_and_email_scrapper.ipynb (unless otherwise specified).

__all__ = ['phoneRegEx', 'emailRegEx', 'text', 'listOfAllPhoneNumbers', 'allPhoneNumbers', 'allEmailAddresses',
           'results']

# Cell
#! python3
import re, pyperclip

#Create a Regex object for phone numbers
phoneRegEx = re.compile(r'''
# 415-555-0000, 555-0000, (415) 555-0000, 555-0000 ext 12345, ext. 1235, x12345

(# adding everything to be part of 1 large group to bypass the "findall" to tuple dynamic
((\d\d\d)|\((\d\d\d)\))?    # area code (optional)
( |-)                      # first separator
(\d\d\d)                    # first 3 digits
-                           # second separator
(\d\d\d\d)                  # last 4 digits
(\s(ext\.?|x)\s)?           # extension word part (optional)
(\d{2,5})?                  # extension number part (optional)
)# end of adding everything to be part of 1 large group to bypass the "findall" to tuple dynamic
''', re.VERBOSE)
#TO DO: Create a Regex object for phone email addresses
emailRegEx = re.compile(r'''
# some.+_thing@some.+_thingcom
[a-zA-Z0-9.+_]+         #name part
@                       # @ symbol
[a-zA-Z0-9.+_]+\.[com|org|edu]+    # domain part
''', re.VERBOSE)
#extract the email /phonr off the clipboard
text = pyperclip.paste()

#: Extract email / phone from this text

listOfAllPhoneNumbers = []

allPhoneNumbers = phoneRegEx.findall(text)
for phoneNumber in allPhoneNumbers:
    listOfAllPhoneNumbers.append(phoneNumber[0])

allEmailAddresses = emailRegEx.findall(text)

# DEBUG: print(listOfAllPhoneNumbers)
# DEBUG:  print(allEmailAddresses)

#Copy extracted list back to the clipboard
results = '\n'.join(listOfAllPhoneNumbers) + '\n' + '\n'.join(allEmailAddresses)
# DEBUG: print(results)
pyperclip.copy(results)