# AUTOGENERATED! DO NOT EDIT! File to edit: 09_Python_command_line.ipynb (unless otherwise specified).

__all__ = ['hello_world']

# Cell
#! python3
def hello_world():
    print("Hello World!")

hello_world()